/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SplashscreenImport } from './routes/splashscreen'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SplashscreenRoute = SplashscreenImport.update({
  id: '/splashscreen',
  path: '/splashscreen',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/splashscreen': {
      id: '/splashscreen'
      path: '/splashscreen'
      fullPath: '/splashscreen'
      preLoaderRoute: typeof SplashscreenImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/splashscreen': typeof SplashscreenRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/splashscreen': typeof SplashscreenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/splashscreen': typeof SplashscreenRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/splashscreen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/splashscreen'
  id: '__root__' | '/' | '/splashscreen'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplashscreenRoute: typeof SplashscreenRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplashscreenRoute: SplashscreenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/splashscreen"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/splashscreen": {
      "filePath": "splashscreen.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
